### ISSUE TITLE
firefox version please ?

### ISSUE THREAD

**Issue by Puppetie** [kazcfz/Copy-n-Paste#10]
i really need this extension but im a firefox user please make it work here

**Comment by kazcfz** [comment]
Will definitely look into making it available for Firefox too. Thanks for your feedback!

**Comment by Puppetie** [comment]
tysm

**Comment by kazcfz** [comment]
The Firefox release is now publicly available! Do give it a try and let me know if you run into any issue

<a href="https://addons.mozilla.org/en-US/firefox/addon/copy-n-paste/"><img src="https://blog.mozilla.org/addons/files/2020/04/get-the-addon-fx-apr-2020.svg" alt="Get Copy-n-Paste for Firefox" height="60px"></a>

So far, 1 known issue is the inability to paste multiple files in 1 copy due to an [old Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=864052)
